// Google Fonts에서 제공하는 'Geist'와 'Geist_Mono' 폰트를 불러옵니다.
// next/font/google 은 Next.js에서 폰트를 최적화하여 사용하는 기능입니다.
import { Geist, Geist_Mono } from "next/font/google";

// 프로젝트 전역 CSS를 불러옵니다.
// 이 파일은 보통 Tailwind CSS 설정, reset.css 등이 포함됩니다.
import "./globals.css";

// Next.js의 Script 컴포넌트는 <script> 태그를 삽입할 때 성능 최적화를 위해 사용됩니다.
// 예: GA, Clarity 등의 외부 스크립트 삽입 시 사용
import Script from "next/script";

// Geist Sans 폰트를 설정합니다.
// variable 속성을 통해 이 폰트를 전역 CSS 변수로 설정합니다. (--font-geist-sans)
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"], // 라틴 문자 서브셋만 로드하여 성능 최적화
});

// Geist Mono (모노스페이스 폰트, 코드용) 설정
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"], // 라틴 문자 서브셋만 로드
});

// 메타데이터는 Next.js의 App Router에서 자동으로 <head>에 삽입됩니다.
export const metadata = {
  title: "Create Next App", // 기본 웹사이트 제목
  description: "Generated by create next app", // 기본 웹사이트 설명 (SEO에 사용됨)
};

// 환경변수에서 Google Analytics ID를 불러옵니다.
// `.env.local` 파일에 NEXT_PUBLIC_GA_ID=G-XXXXXXX 형식으로 저장되어 있어야 합니다.
const GA_ID = process.env.NEXT_PUBLIC_GA_ID;

// 루트 레이아웃 컴포넌트입니다.
// 모든 페이지는 이 컴포넌트를 기반으로 렌더링됩니다.
// App Router 환경에서 `app/layout.tsx` 또는 `app/layout.js` 가 여기에 해당됩니다.
export default function RootLayout({ children }) {
  return (
    // HTML 최상단 요소
    <html lang="en">
      <head>
        {/* Google Analytics의 gtag.js 스크립트를 불러옵니다.
            afterInteractive 전략은 페이지가 인터랙티브(사용자와 상호작용 가능한 상태)가 된 후에 스크립트를 로드합니다. */}
        <Script
          src={`https://www.googletagmanager.com/gtag/js?id=${GA_ID}`}
          strategy="afterInteractive"
        />

        {/* Microsoft Clarity 스크립트 삽입
            사용자 행동 분석 도구로, heatmap이나 세션 리플레이 기능을 제공합니다. */}
        <Script
          id="clarity-script" // 이 스크립트의 고유 식별자
          strategy="afterInteractive" // 페이지 로드 후에 비동기로 실행
          dangerouslySetInnerHTML={{
            __html: `(function(c,l,a,r,i,t,y){
              c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
              t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
              y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
            })(window, document, "clarity", "script", "s4cq3gtajd");`,
          }}
        />

        {/* Google Analytics 설정 스크립트 삽입
            window.dataLayer 초기화 후 gtag로 이벤트를 전송할 수 있도록 설정 */}
        <Script
          id="google-analytics"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date()); // GA 초기화
              gtag('config', '${GA_ID}'); // 설정된 ID로 페이지 뷰 전송
            `,
          }}
        />
      </head>

      {/* 실제 화면을 렌더링하는 body 태그 */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* children은 모든 하위 페이지가 여기에 삽입됩니다.
            예: page.tsx / page.js 등에서 반환하는 컴포넌트 */}
        {children}
      </body>
    </html>
  );
}
